services:
    _defaults:
        public: true

    gett.myparcelbe.service.consignment.download:
        class: Gett\MyparcelBE\Service\Consignment\Download
        arguments:
            - "@=service('prestashop.adapter.legacy.configuration').get(parameter('configuration.api_key_name'))"
            - '@=service("request_stack").getCurrentRequest()'
            - "@=service('prestashop.adapter.legacy.configuration')"

    gett.myparcelbe.service.consignment.update:
        class: Gett\MyparcelBE\Service\Consignment\Update
        arguments:
            - "@=service('prestashop.adapter.legacy.configuration').get(parameter('configuration.api_key_name'))"
            - "@doctrine.orm.entity_manager"
            - "@gett.myparcelbe.service.myparcel_status_provider"

    gett.myparcelbe.factory.consignment_factory:
        class: Gett\MyparcelBE\Factory\Consignment\ConsignmentFactory
        arguments:
            - "@=service('prestashop.adapter.legacy.configuration').get(parameter('configuration.api_key_name'))"
            - '@=service("request_stack").getCurrentRequest()'
            - "@=service('prestashop.adapter.legacy.configuration')"

    gett.myparcelbe.repository.order_label_repository:
        class: Gett\MyparcelBE\Repository\OrderLabelRepository
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    gett.myparcelbe.service.myparcel_status_provider:
        class: Gett\MyparcelBE\Service\MyparcelStatusProvider

    gett.myparcelbe.service.order.order_status_change:
        class: Gett\MyparcelBE\Service\Order\OrderStatusChange

    gett.myparcelbe.order_label_listener:
        class: Gett\MyparcelBE\Listener\MyparcelOrderLabelListener
        arguments:
            - '@gett.myparcelbe.service.order.order_status_change'
            - "@=service('prestashop.adapter.legacy.configuration')"
        tags:
            - { name: doctrine.orm.entity_listener }

    gett.myparcelbe.service.consignment.create:
        class: Gett\MyparcelBE\Service\Consignment\Create
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gett.myparcelbe.service.myparcel_status_provider"
            - "@gett.myparcelbe.factory.consignment_factory"