admin_productmyparcel_save:
    path: myparcel/{productId}/save
    methods: [POST]
    defaults:
        _controller: Gett\Myparcel\Controllers\Admin\ProductCombinatorController::saveProduct
        _legacy_controller: AdminMyparcelController
        _legacy_link: AdminMyparcelProduct:saveProduct
        _legacy_parameters:
            id_product: productId
    requirements:
        id: \d+

#admin_myparcel_orders_label_bulk_create:
#    path: /create-label-bulk
#    methods: [POST]
#    defaults:
#        _controller: Gett\MyparcelBE\Controllers\Admin\LabelController::createLabelsBulk
#        _legacy_controller: AdminMyParcelBELabelController
#        _legacy_link: AdminMyParcelBELabel:createLabelsBulk

#admin_myparcel_orders_label_bulk_print:
#    path: /print-label-bulk
#    methods: [POST]
#    defaults:
#        _controller: Gett\MyparcelBE\Controllers\Admin\LabelController::downloadLabelsBulk
#        _legacy_controller: AdminMyParcelBELabelController
#        _legacy_link: AdminMyParcelBELabel:downloadLabelsBulk

#admin_myparcelbe_order_label_create:
#    path: /create-label
#    methods: [POST]
#    defaults:
#        _controller: Gett\MyparcelBE\Controllers\Admin\LabelController::createLabel
#        _legacy_controller: AdminMyParcelBELabel
#        _legacy_link: AdminMyParcelBELabel:createLabel


#admin_myparcelbe_order_label_download:
#    path: /download-label
#    methods: [POST]
#    defaults:
#        _controller: Gett\MyparcelBE\Controllers\Admin\LabelController::downloadLabel
#        _legacy_controller: AdminMyParcelBELabelController
#        _legacy_link: AdminMyParcelBELabel:downloadLabel

#admin_myparcelbe_order_label_refresh:
#    path: /refresh-label/{labelId}
#    methods: [GET]
#    defaults:
#        _controller: Gett\MyparcelBE\Controllers\Admin\LabelController::updateLabel
#        _legacy_controller: AdminMyParcelBELabelController
#        _legacy_link: AdminMyParcelBELabel:updateLabel

#admin_myparcel_orders_label_bulk_refresh:
#    path: /refresh-label-bulk
#    methods: [POST]
#    defaults:
#        _controller: Gett\MyparcelBE\Controllers\Admin\LabelController::refreshLabelsBulk
#        _legacy_controller: AdminMyParcelBELabelController
#        _legacy_link: AdminMyParcelBELabel:refreshLabelsBulk