name: 'Run tests ðŸ§ª'
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || '' }}

      - uses: myparcelnl/actions/build-docker-image@v2
        id: docker
        with:
          image: myparcel/sdk
          key: php-sdk
          docker-args: --target test

      - name: 'Create .env file'
        run: |
          cat << EOF > .env
          CI=${CI}
          API_KEY_NL=${{ secrets.API_KEY_NL }}
          API_KEY_BE=${{ secrets.API_KEY_BE }}
          EOF

      - name: 'Run tests'
        run: docker run --env-file .env ${{ steps.docker.outputs.tagged_image }}

      - name: 'Get coverage file from container'
        run: docker cp $(docker ps -alq):/app/coverage.xml .

      - name: 'Update code coverage'
        uses: codecov/codecov-action@v2
